### PR TITLE
Fix of some few missing username & comment in comments

### LINKED ISSUE #2: Content and username is not visible on few comments
image

### PR DESCRIPTION
**Pull request by nch3ng**
Closes #2
Caused by some already deleted comment in responded data.  Send back the comment id to the parent, and remove it from array.  Please review, and see if there's any concern.

### CODE REVIEW

File: src/app/components/story-feed-item-detail/story-feed-item-detail.component.ts [hunk 1]
```diff
@@ -40,4 +40,8 @@ export class StoryFeedItemDetailComponent implements OnInit {
       );
     });
   }
+
+  onDeleted(comment_id) {
```
Comment (kapillamba4) [inline src/app/components/story-feed-item-detail/story-feed-item-detail.component.ts]: @qqnc, This looks good to me but i think you will need to add onDeleted method to CollapsibleListComponent also along with changes to its html file to completely fix this issue

Comment (nch3ng) [reply src/app/components/story-feed-item-detail/story-feed-item-detail.component.ts]: @kapillamba4 What do you mean add onDeleted method and changes to its html? I did first change for just add *ngIf in CollapsibleListComponent.  However, the wrapper in StoryFeedItemDetailComponent will still be there.  Nothing bad, just it was not the best way. So I decided to emit the delete item to StoryFeedItemDetailComponent to completely remove it for parent.  Now sure what you mean.  May you elaborate a little bit?

Comment (kapillamba4) [reply src/app/components/story-feed-item-detail/story-feed-item-detail.component.ts]: CollapsibleListComponent can be child Component of either [CollapsibleListComponent](https://github.com/kapillamba4/hackernews-clone/blob/master/src/app/components/collapsible-list/collapsible-list.component.html#L15) or [StoryFeedItemDetailComponent](https://github.com/kapillamba4/hackernews-clone/blob/master/src/app/components/story-feed-item-detail/story-feed-item-detail.component.html#L14). That is why you will need to add onDeleted method to CollapsibleListComponent and bind event handler in [html file](https://github.com/kapillamba4/hackernews-clone/blob/master/src/app/components/story-feed-item-detail/story-feed-item-detail.component.html#L14)
image

**Comment by nch3ng** [comment]
I missed that part, and added an onDeleted method into CollapsibleList Component and its html.

**Comment by kapillamba4** [comment]
Looks good :+1: , Thanks for your contribution!
